config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :products, only: [:index, :show] do
    post :add_to_cart, on: :member
    post :delete_from_cart, on: :member
    post :change_cart_item, on: :member
  end   
  resource :cart
  resource :order
  root "products#index"

  namespace :admin do
    resources :products
    resources :orders
    root "products#index"
  end  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items

  def add_cart_item(product)
    existing_item = self.cart_items.find_by(product_id: product)
    if existing_item
      existing_item.quantity += 1
      existing_item.save!
    else
      cart_item = cart_items.build( product_id: product.id)
      cart_item.save!
    end  
    self.cart_items
  end

  def subtotal
    self.cart_items.to_a.sum(&:subtotal)

  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  def subtotal
    self.quantity * self.product.price
  end
end  

app/models/cartitem.rb
class Cartitem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :orderitems, dependent: :destroy
  has_many :payments
end

app/models/orderitem.rb
class Orderitem < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ProductImageUploader
  validates_presence_of :name, :description, :price

  has_many :cart_items, dependent: :destroy
  has_many :carts, through: :cart_items
  has_many :order_items, dependent: :destroy
  has_many :orders, through: :order_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders
  
  def admin?
    self.role == "admin"
  end       
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
    before_action :authenticate_user!
    before_action :authenticate_admin

  def index
    @orders = Order.page(params[:page]).per(12)     
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  helper_method :current_cart # call the helper in all views

  
  private

  def authenticate_admin
    unless current_user.admin?
      flash[:alert] = "Not allow!"
      redirect_to root_path
    end
  end

  def current_cart
    @cart || set_cart # return @cart if @cart exist, or call set_cart
  end

  def set_cart

    if session[:cart_id]
      @cart = Cart.find_by(id: session[:cart_id])
    end

    @cart ||= Cart.create

    session[:cart_id] = @cart.id
    @cart
  end
  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order = Order.new
  end
  
end

app/controllers/oders_controller.rb
class OdersController < ApplicationController

end

app/controllers/orderitems_controller.rb
class OrderitemsController < ApplicationController
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.page(params[:page]).per(12) 
  end

  def show
    @product = Product.find(params[:id])
  end

  def add_to_cart
    @product = Product.find(params[:id])
    current_cart.add_cart_item(@product)

    redirect_back(fallback_location: root_path)
  end
  
  def delete_from_cart
    cart_item = CartItem.find_by(params[:id])
    cart_item.destroy
    redirect_back(fallback_location: root_path)
  end

  def change_cart_item
    @product = Product.find(params[:id])
    cart_item = CartItem.find_by(product: @product)
    if params[:type] == "add"
      cart_item.quantity += 1
    elsif params[:type] == "reduce"
      cart_item.quantity -= 1
    end
    
    if cart_item.quantity == 0
      cart_item.destroy
    else
      cart_item.save!
    end  
    redirect_back(fallback_location: root_path)        
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/oders_helper.rb
module OdersHelper
end

app/helpers/orderitems_helper.rb
module OrderitemsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/orders/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>E-commerce Project</title>
</head>
<body>
  <p>Edit Order</p>
</body>
</html>

app/views/admin/orders/index.html.erb
<div class="container">
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <%= link_to'Order list', admin_orders_path, class: "nav-link active" %>
    </li>
    <li class="nav-item">
      <%= link_to'Product list', admin_root_path, class: "nav-link" %>
    </li>
  </ul>

  <table class="table table-hover">
     <thead class="thead-light ">
      <tr>
        <th>Order Number</th>
        <th>Price</td>
        <th>Payment status</td>
        <th>Shipping status</td>
        <th>Order Details</td>
      </tr>
    </thead>
    <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td>
          #<%= order.sn %>
        </th>
        <td>
          $<%= order.price%>
        </td>
        <td>
          order.payment_status
        </td>    
        <td>
          order.Shipping_status
        </td>
        <td><%= link_to 'Edit Detail', edit_admin_order_path(order) %>    
        </td>  
      </tr>
    <% end %>
    </tbody>
  </table>
  <div class="container pagination justify-content-center" >
    <%= paginate @orders, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm" %>
  </div>
</div>