config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :products, only: [:index, :show] do
    post :add_to_cart, on: :member
    post :delete_from_cart, on: :member
    post :change_cart_item, on: :member
  end   
  resource :cart
  resource :order
  root "products#index"

  namespace :admin do
    resources :products
    resources :orders
    root "products#index"
  end  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items

  def add_cart_item(product)
    existing_item = self.cart_items.find_by(product_id: product)
    if existing_item
      existing_item.quantity += 1
      existing_item.save!
    else
      cart_item = cart_items.build( product_id: product.id)
      cart_item.save!
    end  
    self.cart_items
  end

  def subtotal
    self.cart_items.to_a.sum(&:subtotal)

  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  def subtotal
    self.quantity * self.product.price
  end
end  

app/models/cartitem.rb
class Cartitem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :orderitems, dependent: :destroy
  has_many :payments
end

app/models/orderitem.rb
class Orderitem < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ProductImageUploader
  validates_presence_of :name, :description, :price

  has_many :cart_items, dependent: :destroy
  has_many :carts, through: :cart_items
  has_many :order_items, dependent: :destroy
  has_many :orders, through: :order_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders
  
  def admin?
    self.role == "admin"
  end       
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
    before_action :authenticate_user!
    before_action :authenticate_admin

  def index
    @orders = Order.page(params[:page]).per(12)     
  end  
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin

  def index
    @products = Product.page(params[:page]).per(12)
    
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_products_path, notice: "Product published successfully"
    else
      render :new, alert: "Product was dailed to create"
    end  
  end

  def edit
     @product = Product.find(params[:id])
  end
  
  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to admin_products_path(@product), notice: "Product was successfully updated"
    else
      render :edit, alert: "Product was failed to update"
    end  
  end 

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to admin_products_path, alert: "Product deleted!"
  end  

  private
  def product_params
    params.require(:product).permit(:name, :image, :description, :price)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  helper_method :current_cart # call the helper in all views

  
  private

  def authenticate_admin
    unless current_user.admin?
      flash[:alert] = "Not allow!"
      redirect_to root_path
    end
  end

  def current_cart
    @cart || set_cart # return @cart if @cart exist, or call set_cart
  end

  def set_cart

    if session[:cart_id]
      @cart = Cart.find_by(id: session[:cart_id])
    end

    @cart ||= Cart.create

    session[:cart_id] = @cart.id
    @cart
  end
  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order = Order.new
  end
  
end

app/controllers/oders_controller.rb
class OdersController < ApplicationController

end

app/controllers/orderitems_controller.rb
class OrderitemsController < ApplicationController
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.page(params[:page]).per(12) 
  end

  def show
    @product = Product.find(params[:id])
  end

  def add_to_cart
    @product = Product.find(params[:id])
    current_cart.add_cart_item(@product)

    redirect_back(fallback_location: root_path)
  end
  
  def delete_from_cart
    cart_item = CartItem.find_by(params[:id])
    cart_item.destroy
    redirect_back(fallback_location: root_path)
  end

  def change_cart_item
    @product = Product.find(params[:id])
    cart_item = CartItem.find_by(product: @product)
    if params[:type] == "add"
      cart_item.quantity += 1
    elsif params[:type] == "reduce"
      cart_item.quantity -= 1
    end
    
    if cart_item.quantity == 0
      cart_item.destroy
    else
      cart_item.save!
    end  
    redirect_back(fallback_location: root_path)        
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/oders_helper.rb
module OdersHelper
end

app/helpers/orderitems_helper.rb
module OrderitemsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<div class="container">
  <div class="row">

    <% if @product.errors.any? %>
      <h4>We have some errors here !</h4>
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
      <hr>
    
    <% end %>      
    <%= form_for [:admin, @product] do |f| %>
      <div class="form_group">
        <%= f.label :name, "Product Name" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="form_group">        
        <%= f.label :image, "Product Photo" %>
        <%= image_tag @product.image, width: '300px' if @product.image? %>
        <%= f.file_field :image %>
      </div>

      <div class="form_group">
        <%= f.label :description, "Description" %>
        <%= f.text_area :description, class: "form-control" %></textarea>
      </div>

      <div class="form_group">
        <%= f.label :price, "Price" %>
        <%= f.text_field :price, class: "form-control" %>
      </div>
      <br>
      <div class="form-group">
        <%= f.submit class: "btn btn-primary" %>
        <%= f.button 'cancel', type: :reset, class: "btn btn-default" %>
      </div>
    <% end %>
  </div>
</div> 

app/views/admin/products/edit.html.erb
<%= render partial: "form" %>

app/views/admin/products/index.html.erb
<div class="container">
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <%= link_to'Order list', admin_orders_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to'Product list', admin_root_path, class: "nav-link active" %>
    </li>
    <li><%= link_to'+ Add new product', new_admin_product_path, class:"btn btn-primary" %>
    </li>
  </ul>

  <table class="table table-hover">
     <thead class="thead-light ">
      <tr>
        <th class="col">Product name</th>
        <th class="col">Image</th>
        <th class="col">Price</th>
        <th class="col">Edit</th>
        <th class="col">Delete</th>
      </tr>
    </thead>
    <tbody>
    <% @products.each do |product| %>
      <tr>
        <td>
          <%= link_to product_path(product) do %>@<%= product.name %><% end %>
        </th>
        <td>
          <% if product.image? %>
            <%= image_tag product.image, width: '100px', class: "rounded m-auto d-block" %>
          <% else %>
            <h4 class="text-center">No Product Image</span></h1>
          <% end %>
        </td>
        <td><%= product.price %></td>       
        <td><%= link_to 'Edit', edit_admin_product_path(product), class: "text-center" %>    
        </td>
        <td><%= link_to 'Delet', admin_product_path(product), method: :delete, data:{ confirm: "確定刪除?" }, class: "text-center" %>    
        </td>  
      </tr>
    <% end %>
    </tbody>
  </table>
  <div class="container pagination justify-content-center" >
    <%= paginate @products, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm" %>
  </div>
</div>

app/views/admin/products/new.html.erb
<%= render partial: "form" %>

app/views/products/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-sm-10">
      <!-- all products display -->
      <div class="row">
      <% @products.each do |product| %>
        <div class="col-6 col-sm-4 col-md-3 mb-3">
          <div class="card opacity_white">
            <% if product.image? %>
              <%= image_tag product.image, height:'50%', class: "card-img-top" %>
            <% else %>
              <img  class="card-img-top" src="http://via.placeholder.com/350x235">
            <% end %>
            <div class="card-body">
              <h5 class="card-title"><%= link_to product.name, product_path(product) %></h5> 
              <p class="card-text"><%= truncate(product.description, length: 10) %></p>
              <h2 class="card-text">$ <%= product.price %></h2>
              
            </div>
            <h5 class="card-footer"><%= button_to "Add to Cart", add_to_cart_product_path(product) %></h5> 
          </div>
        </div>
      <% end %>
      </div>
      <!-- 有generate kaminari paginate bootstrap style -->
      <br/>
      <div class="pagination justify-content-center">
        <%= paginate @products, theme: 'twitter-bootstrap-4' %>
      </div>
    </div>
    <div class="col-6 col-sm-2">
      <!-- sideCart -->
      <%= render partial: "shared/side_cart" %>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="container">
  <!-- product detail -->
  <div class="row ">
    <!-- product's image -->
    <div class="col-12 col-md-5 ">
      <% if @product.image? %>
        <%= image_tag @product.image, width: '350px', class: "img-responsive center-block" %>
      <% else %>
        <img  class="card-img-top" src="http://via.placeholder.com/350x235">
      <% end %>
    </div>  

    <!-- product's details -->
    <div class="col-12 col-sm-5 ">
      <ul class="list-unstyled">
        <li><h1><%= @product.name %></h1></li>
        <li><h4>$<%= @product.price %></h4></li>
        <li><%= @product.description%></li>
      </ul>
       
      <!-- quantity change and add to cart form-->
      <p>- 1 +</p>
      <%= button_to 'Add to Cart', add_to_cart_product_path(@product) %>
    </div>

    <div class="col-6 col-sm-2">
      <!-- sideCart -->
      <%= render partial: "shared/side_cart" %>
    </div>
  </div>   
</div>  