config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :products, only: [:index, :show] do
    post :add_to_cart, on: :member
    post :delete_from_cart, on: :member
    post :change_cart_item, on: :member
  end   
  resource :cart
  resource :order
  root "products#index"

  namespace :admin do
    resources :products
    resources :orders
    root "products#index"
  end  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items

  def add_cart_item(product)
    existing_item = self.cart_items.find_by(product_id: product)
    if existing_item
      existing_item.quantity += 1
      existing_item.save!
    else
      cart_item = cart_items.build( product_id: product.id)
      cart_item.save!
    end  
    self.cart_items
  end

  def subtotal
    self.cart_items.to_a.sum(&:subtotal)

  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  def subtotal
    self.quantity * self.product.price
  end
end  

app/models/cartitem.rb
class Cartitem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :orderitems, dependent: :destroy
  has_many :payments
end

app/models/orderitem.rb
class Orderitem < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ProductImageUploader
  validates_presence_of :name, :description, :price

  has_many :cart_items, dependent: :destroy
  has_many :carts, through: :cart_items
  has_many :order_items, dependent: :destroy
  has_many :orders, through: :order_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders
  
  def admin?
    self.role == "admin"
  end       
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order = Order.new
  end
  
end

app/controllers/oders_controller.rb
class OdersController < ApplicationController

end

app/controllers/orderitems_controller.rb
class OrderitemsController < ApplicationController
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.page(params[:page]).per(12) 
  end

  def show
    @product = Product.find(params[:id])
  end

  def add_to_cart
    @product = Product.find(params[:id])
    current_cart.add_cart_item(@product)

    redirect_back(fallback_location: root_path)
  end
  
  def delete_from_cart
    cart_item = CartItem.find_by(params[:id])
    cart_item.destroy
    redirect_back(fallback_location: root_path)
  end

  def change_cart_item
    @product = Product.find(params[:id])
    cart_item = CartItem.find_by(product: @product)
    if params[:type] == "add"
      cart_item.quantity += 1
    elsif params[:type] == "reduce"
      cart_item.quantity -= 1
    end
    
    if cart_item.quantity == 0
      cart_item.destroy
    else
      cart_item.save!
    end  
    redirect_back(fallback_location: root_path)        
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/oders_helper.rb
module OdersHelper
end

app/helpers/orderitems_helper.rb
module OrderitemsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>ECommerce</title>
  <meta name='viewport' content='width=devise-width, initial-scale=1.0'>
  <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <!-- nav bar -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color: #e3f2fd;">
    <%= link_to'E-commerce', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">  
        <li class="nav-item">
          <p class="navbar-text">Hi, 
            <% if current_user %>
              <%= current_user.email %>
            <% else %>
              visitor
            <% end %>  
          </p>
        </li>
        <% if current_user && current_user.admin? %>
          <li class="nav-item">
            <%= link_to'Admin Panel', admin_root_path, class: "nav-link" %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to 'Cart', cart_path, class: "nav-link"  %> 
        </li>
        <li class="nav-item">
          <%= link_to 'Order', order_path, class: "nav-link" %> 
        </li>
        <% if current_user %>
          <li class="nav-item">
            <%= link_to'登出', destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to'修改密碼', edit_user_registration_path, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to'註冊', new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to'登入', new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
  <!-- 用flash提示action訊息 -->
  <% if flash[:notice] %>
    <div class="container">
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= notice %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
      </div>
    </div>
    <% end %>
      <!-- 用flash提示錯誤警告訊息 -->
      <% if flash[:alert] %>
        <div class="container">
          <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <%= alert %>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
          </div>
        </div>
        <% end %>
          <!-- 呼叫action對應之html.erb -->
          <%= yield %>
</body>

</html>

app/views/shared/_side_cart.html.erb
<h2>Cart</h2>
<hr>

<!-- cart_items list -->
<ul class="list-unstyled">
<% current_cart.cart_items.each do |cart_item| %>
  <li class="media">
    <% if cart_item.product.image? %>
      <%= image_tag cart_item.product.image, width:"50 px", class: "mr-3" %>
    <% else %>
      <img  class="mr-3" src="http://via.placeholder.com/50x35">
    <% end %>
    <div class="media-body">
      <h5><%= cart_item.product.name %></h5>
      <p>$<%= cart_item.product.price %></p>
      <%= link_to ' - ', change_cart_item_product_path(cart_item.product, type: 'reduce'), method: :post, class: "badge badge-pill badge-secondary" %>
      <%= cart_item.quantity %>
      <%= link_to ' + ', change_cart_item_product_path(cart_item.product, type: 'add'), method: :post, class: "badge badge-pill badge-secondary" %>
      <%= button_to 'Delete', delete_from_cart_product_path(cart_item.product) %>
    </div>
  </li>
<% end %>
</ul>
<hr>
<!-- totals and cart link -->
<h5>subtotal $<%= current_cart.subtotal %></h5>